import { VendorReport } from "./types";

export const mockReports: VendorReport[] = [
  {
    id: "1",
    propertyAddress: "42 Oceanview Drive, Brighton VIC 3186",
    vendorName: "John & Sarah Mitchell",
    agent: "Stuart Grant",
    weekEnding: "2026-03-01",
    listingDate: "2026-02-01",
    askingPrice: "$1,850,000 - $2,035,000",
    reaViews: 1243,
    reaEnquiries: 18,
    reaSaves: 67,
    reaSearchAppearances: 4521,
    domainViews: 876,
    domainEnquiries: 12,
    domainSaves: 43,
    domainSearchAppearances: 3210,
    openHomeAttendees: 24,
    privateInspections: 6,
    campaignType: "Auction",
    daysOnMarket: 28,
    messages: [
      {
        id: "m1",
        sender: "Stuart Grant",
        senderRole: "agent",
        message: "Great open home this weekend - 24 groups through. Strong interest from 3 buyers.",
        timestamp: "2026-03-01T10:30:00",
      },
      {
        id: "m2",
        sender: "John Mitchell",
        senderRole: "vendor",
        message: "Thanks Stuart, that sounds promising. Any offers yet?",
        timestamp: "2026-03-01T11:15:00",
      },
    ],
  },
  {
    id: "2",
    propertyAddress: "15 Elm Street, Hawthorn VIC 3122",
    vendorName: "David Chen",
    agent: "Stuart Grant",
    weekEnding: "2026-03-01",
    listingDate: "2026-02-15",
    askingPrice: "$1,200,000 - $1,320,000",
    reaViews: 892,
    reaEnquiries: 14,
    reaSaves: 51,
    reaSearchAppearances: 3100,
    domainViews: 654,
    domainEnquiries: 9,
    domainSaves: 32,
    domainSearchAppearances: 2450,
    openHomeAttendees: 18,
    privateInspections: 3,
    campaignType: "Private Sale",
    daysOnMarket: 14,
    messages: [
      {
        id: "m3",
        sender: "Stuart Grant",
        senderRole: "agent",
        message: "Solid first two weeks David. Online engagement is above average for the area.",
        timestamp: "2026-03-01T09:00:00",
      },
    ],
  },
  {
    id: "3",
    propertyAddress: "8/120 Chapel Street, St Kilda VIC 3182",
    vendorName: "Lisa Nguyen",
    agent: "Emma Wilson",
    weekEnding: "2026-03-01",
    listingDate: "2026-01-20",
    askingPrice: "$680,000 - $748,000",
    reaViews: 2105,
    reaEnquiries: 27,
    reaSaves: 89,
    reaSearchAppearances: 6200,
    domainViews: 1430,
    domainEnquiries: 19,
    domainSaves: 61,
    domainSearchAppearances: 4800,
    openHomeAttendees: 31,
    privateInspections: 8,
    campaignType: "Auction",
    daysOnMarket: 40,
    messages: [],
  },
  {
    id: "4",
    propertyAddress: "27 Parkview Crescent, Camberwell VIC 3124",
    vendorName: "Robert & Jane Taylor",
    agent: "Stuart Grant",
    weekEnding: "2026-03-01",
    listingDate: "2026-02-22",
    askingPrice: "$2,400,000 - $2,640,000",
    reaViews: 567,
    reaEnquiries: 8,
    reaSaves: 29,
    reaSearchAppearances: 1890,
    domainViews: 412,
    domainEnquiries: 5,
    domainSaves: 18,
    domainSearchAppearances: 1560,
    openHomeAttendees: 9,
    privateInspections: 4,
    campaignType: "Expressions of Interest",
    daysOnMarket: 7,
    messages: [],
  },
];
